author: "Vincent Chin"
email: "vincent4552@gmail.com"

theme: minima

github_username: Vincexodus

minima:
  date_format: "%Y-%m-%d"

header_pages:
  - _pages/frontpage.md

include:
  - _pages

exclude: 
  - .gitignore
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md